### ISSUE TITLE
output to .json fails

### ISSUE THREAD

**Issue by erikbrodnick** [njanakiev/folderstats#14]
$ folderstats . -i -p -v -c sha1 -o output.json

Traceback (most recent call last):
  File "/usr/local/bin/folderstats", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/folderstats/__main__.py", line 64, in main
    df.to_json(args.output_filepath, index=False)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/generic.py", line 2305, in to_json
    indent=indent,
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/json/_json.py", line 51, in to_json
    "'index=False' is only valid when 'orient' is 'split' or 'table'"
ValueError: 'index=False' is only valid when 'orient' is 'split' or 'table'

**Comment by njanakiev** [comment]
Thanks for the issue @erikbrodnick! This error has been fixed with the latest `0.4.0` release.
